---
namespace: language.corpora.word_freq
protocol: bnc

messages:
  word_stats:
    request:
      - name: word_stats_request
        type: word_stats_request
    response: word_statistics_record
    doc: Query on a head word to get back word statistics (and word variants) from the British National Corpus.

data_assets:
  - name: word_stats_data_asset
    location: data/word_stats
    type: word_statistics_record
      
code_assets:
  - location: code/bnc_endpoint.rb
    name: bnc_endpoint

targets:
  apeyeye:
    - code_assets:
        - bnc_endpoint
  mysql:
    - table_name: bnc
      database: language_corpora_word_freq
      name: word_freq_bnc
      data_assets:
        - word_stats_data_asset
  catalog:
    - name: word_freq_bnc
      title: Word Frequencies From the British National Corpus
      description: >-

        The British National Corpus (BNC) is a 100-million-word text corpus of samples of written and spoken English from a wide range of sources.
        It was compiled as a general corpus (collection of texts) in the field of corpus linguistics. The corpus covers British English the late
        twentieth century from a wide variety of genres with the intention that it be a representative sample of spoken and written British English
        of that time.

        Of the two parts to the 10-million word spoken corpus, one is a demographic part, containing transcriptions of spontaneous natural conversations
        made by members of the public and the other a context-governed part, containing transcriptions of recordings made at specific types of meeting
        and event. All the original recordings transcribed for inclusion in the BNC have been deposited at the British Library Sound Archive.

        In this data set, we provide plain text versions of the frequency lists contained in WFWSE. These are raw unedited frequency lists produced by
        our software and do not contain the many additional notes supplied in the book itself. The lists are tab delimited plain text so can be imported
        into your prefered spreadsheet format. For the main lists we provide a key to the columns. More details on the process undertaken in the preparation
        of the lists can be found in the introduction to the book. These lists show dispersion ranging between 0 and 1 rather than 0 and 100 as in the book.
        We multiplied the value by 100 and rounded to zero decimal places in the book for reasons of space. Log likelihood values are shown here to one
        decimal place rather than zero as in the book. Please note, all frequencies are per million words.
        
      tags:
        - bnc
        - british-national-corpus
        - awesomeapi
        - token
        - word
        - corpus
        - word-frequency
        - british
        - words
        - language
      messages:
        - word_stats

types:
  
  - name: word_stats_request
    type: record
    doc: Query api parameters for the word_stats message
    fields:
      - name: head_word
        type: string
        default: chimpanzee
            
  - name: word_statistics_record
    doc: >-
      Here we provide plain text versions of the frequency lists contained in WFWSE. These are
      raw unedited frequency lists produced by our software and do not contain the many
      additional notes supplied in the book itself. The lists are tab delimited plain text so
      can be imported into your prefered spreadsheet format. For the main lists we provide a
      key to the columns. More details on the process undertaken in the preparation of the
      lists can be found in the introduction to the book. These lists show dispersion ranging
      between 0 and 1 rather than 0 and 100 as in the book. We multiplied the value by 100 and
      rounded to zero decimal places in the book for reasons of space. Log likelihood values
      are shown here to one decimal place rather than zero as in the book. Please note, all
      frequencies are per million words.
    type: record
    fields:
      - name: head_word
        doc:  Word type headword - see pp.4-5
        type: string
      - name: part_of_speech
        doc: Part of speech (grammatical word class - see pp. 12-13)
        type: string
      - name: head_word_freq_ppm
        doc:  Rounded frequency per million word tokens (down to a minimum of 10 occurrences of a lemma per million)- see pp. 5. Where BOTH head word and lemmas appear
        type: float
      - name: head_word_range
        doc: Range, the number of sectors of the corpus (out of a maximum of 100) in which the word occurs. Where BOTH head word and lemmas appear
        type: int
      - name: head_word_dispersion
        doc: Dispersion value (Juilland's D) from a minimum of 0.00 to a maximum of 1.00. Where BOTH head word and lemmas appear
        type: float
      - name: variant_word
        doc: Variant form of headword
        type: string
      - name: variant_word_freq_ppm
        doc:  Rounded frequency per million word tokens (down to a minimum of 10 occurrences of a lemma per million)- see pp. 5. Where BOTH head word and lemmas appear
        type: float
      - name: variant_word_range
        doc: Range, the number of sectors of the corpus (out of a maximum of 100) in which the word occurs. Where BOTH head word and lemmas appear
        type: int
      - name: variant_word_dispersion
        doc: Dispersion value (Juilland's D) from a minimum of 0.00 to a maximum of 1.00. Where BOTH head word and lemmas appear
        type: float


# not included in the output icss
filesystem_scheme: file
non_avro:
  download_url: http://ucrel.lancs.ac.uk/bncfreq/lists/1_1_all_fullalpha.txt.Z
